# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/vigenere.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(725, 567)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 290, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(200, 30, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 230, 55, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.key_txt = QtWidgets.QLineEdit(Dialog)
        self.key_txt.setGeometry(QtCore.QRect(150, 240, 531, 22))
        self.key_txt.setObjectName("key_txt")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(240, 70, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.plaintext_txt = QtWidgets.QPlainTextEdit(Dialog)
        self.plaintext_txt.setGeometry(QtCore.QRect(150, 120, 531, 87))
        self.plaintext_txt.setObjectName("plaintext_txt")
        self.ciphertext_txt = QtWidgets.QPlainTextEdit(Dialog)
        self.ciphertext_txt.setGeometry(QtCore.QRect(150, 290, 531, 171))
        self.ciphertext_txt.setObjectName("ciphertext_txt")
        self.encrypt_btn = QtWidgets.QPushButton(Dialog)
        self.encrypt_btn.setGeometry(QtCore.QRect(210, 510, 93, 28))
        self.encrypt_btn.setObjectName("encrypt_btn")
        self.decrypt_btn = QtWidgets.QPushButton(Dialog)
        self.decrypt_btn.setGeometry(QtCore.QRect(470, 510, 93, 28))
        self.decrypt_btn.setObjectName("decrypt_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "Cipher text"))
        self.label.setText(_translate("Dialog", "VIGENERE CIPHER"))
        self.label_4.setText(_translate("Dialog", "Key"))
        self.label_2.setText(_translate("Dialog", "Nguyễn Ngọc Trinh - 2280603400"))
        self.label_3.setText(_translate("Dialog", "Plain text"))
        self.encrypt_btn.setText(_translate("Dialog", "Encrypt"))
        self.decrypt_btn.setText(_translate("Dialog", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
